version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: circleci/node:11.9
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ checksum "package.json" }}
      - run:
          name: install
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: deps-{{ checksum "package.json" }}
      - run:
          name: lint
          command: yarn run lint
      - run:
          name: deploy
          command: yarn run deploy
