version: 2

aliases:
  - &docker
    - image: circleci/node:11.9
  - &restore_cache
    restore_cache:
      keys:
        - deps-{{ checksum "package.json" }}
  - &run_yarn
    run:
      name: Yarn
      command: yarn install
  - &attach_workspace
    at: .

jobs:
  setup:
    docker: *docker
    steps:
      - checkout
      - *restore_cache
      - *run_yarn
      - save_cache:
          paths:
            - node_modules
          key: deps-{{ checksum "package.json" }}
  lint:
    docker: *docker
    steps:
      - checkout
      - *restore_cache
      - *run_yarn
      - run:
         name: lint
         command: yarn run lint
  build:
    docker: *docker
    steps:
      - checkout
      - *restore_cache
      - *run_yarn
      - run:
          name: build
          command: yarn run build
      - run:
          name: pwd
          command: pwd
      - run:
          name: ls
          command: ls -lah
      - run:
          name: projectls
          command: ls -lah public
      - persist_to_workspace:
          root: .
          path:
            - .
  deploy:
    docker: *docker
    steps:
      - checkout
      - attach_workspace: *attach_workspace
      - *restore_cache
      - *run_yarn
      - run:
          name: vars
          command: |
            git config user.name $GH_NAME
            git config user.email $GH_EMAIL
            printf "CONTENTFUL_SPACE_ID=$CONTENTFUL_SPACE_ID" > .env.production
            printf "CONTENTFUL_ACCESS_TOKEN=$CONTENTFUL_ACCESS_TOKEN" >> .env.production
      - run:
          name: depoy
          command: yarn run deploy

workflows:
  version: 2
  commit:
    jobs:
      - setup
      - lint:
          requires:
            - setup
      - build:
          requires:
            - setup
      - deploy:
          filters:
            branches:
              only: master
          requires:
            - lint
            - build
